name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go mod download

    - name: Test
      run: go test -v .

    - name: Package
      run: |
        mkdir dist
        BUILD_TIME=$(date -Is)
        PACKAGE_NS="github.com/codingtony/ansible-vault-go"
        VERSION="1.0.${{ github.run_number }}"

        LDFLAGS="-s -w -X  "${PACKAGE_NS}"/cmd.version="${VERSION}" -X "${PACKAGE_NS}"/cmd.buildTime=${BUILD_TIME}"
        
        GOARCH=amd64  
        
        GOOS=darwin
        go build -ldflags="${LDFLAGS}" -o "dist/ansible-vault-go_${GOOS}_${GOARCH}"
        
        GOOS=windows 
        go build -ldflags="${LDFLAGS}" -o "dist/ansible-vault-go_${GOOS}_${GOARCH}.exe"
        
        GOOS=linux
        go build -ldflags="${LDFLAGS}" -o "dist/ansible-vault-go_${GOOS}_${GOARCH}"
        
        tar -C dist -cvf ansible-vault-go.tar .


    - name: Create Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ansible-vault-go-1.0.${{ github.run_number }}
        path: |
          ansible-vault-go.tar
          
